import type { MetadataRoute } from "next";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: [
        "/",
        "/colleges",
        "/college/",
        "/app/academics",
        "/app/academics/",
        "/a/",
        "/e/",
        "/app/communities",
        "/app/communities/",
        "/@*",
        "/app/post/",
        "/overview",
        "/pitch",
        "/demo",
        "/about",
        "/safety",
        "/terms",
        "/privacy",
        "/contact",
      ],
      disallow: [
        "/admin",
        "/admin/",
        "/api/",
        "/app/settings",
        "/app/chat",
        "/app/dating",
        "/app/matching",
        "/app/crush",
        "/app/random",
        "/app/marketplace/cart",
        "/app/marketplace/checkout",
        "/app/marketplace/order/",
        "/app/saved",
        "/app/notifications",
        "/app/onboarding",
        "/handler/",
        "/merchant-portal",
        "/merchant-portal/",
        "/invalid-email",
        "/logout",
      ],
    },
    sitemap: "https://campusloop.space/sitemap.xml",
  };
}
